### ISSUE TITLE
what is the use of the linear filter ? 

### ISSUE THREAD

**Issue by 12rambau** [gee-community/geetools#127]
@fitoprincipe I'm refactoring for the v1 of the package the very long and complex image.py file. Could you elaborate on the use of the `linearFunction` I fail to see where it's useful and what it is doing. 

https://github.com/gee-community/gee_tools/blob/d45ad99cedfb3d8e11cf9d972f3d334b94d9ad19/geetools/tools/image.py#L808

thanks for your help!

**Comment by fitoprincipe** [comment]
Probably the naming is confusing. I think `mean` should be `target`. This function was designed to be used in the "Best Available Pixel" (BAP) compositing algorithm.

The idea is the following:

You have a band that has a fixed range. For the example let's use NDVI from 0 to 1. Then, you have a `target` value, which will take the highest "score". For the example let's say `target = 0.8`. Finally, we want the score to be from 0 to 100

``` python
range_min = 0
range_max = 1
mean = 0.8
output_min = 0
output_max = 100

# results
f(0.1) = 12.5
f(0.5) = 62.5
f(0.8) = 100
f(1) = 75
```

And the [`normalDistribution`](https://github.com/gee-community/geetools/blob/d45ad99cedfb3d8e11cf9d972f3d334b94d9ad19/geetools/tools/image.py#L780) function is the same but applying a normal distribution (gaussian) instead of a linear one.
