### ISSUE TITLE
Disappearance of the "batch" module in geetools?

### ISSUE THREAD

**Issue by Shima-shoki** [gee-community/geetools#201]
Hi, I've been a big fun of geetools and especially the batch module is quite nice to automate the data export process. However, I noticed that from the version 1.0, which was released several hours ago, the batch module can't be loaded by "from geetools import batch". I confirmed that it's ok with the version 0.6.14. My coding environment is Google Colab. I very much appreciate any comments or advices with this issue!

**With the version 0.6.14, "from geetools import batch" works**
![image](https://github.com/gee-community/geetools/assets/47880765/ae7b5576-6029-483d-8eb4-4168490cd26d)

**If the geetools version is changed to 1.0.0, "from geetools import batch" shows errors**
![image](https://github.com/gee-community/geetools/assets/47880765/66081797-4c65-427f-b94a-295649f122ad)

**Comment by 12rambau** [comment]
Hi @Shima-shoki and thanks for reporting it. 
Since October the package went through huge changes. We realized it was creating many small mistakes due to the lack of testing. These errors are mostly hidden for interactive interfaces such as colab and juyterlab. I thus started a crusade to recode most of the functions as extensions and start a more robust coding workflow (test, coverage, documentation). Solving the circular imports lead  to modifications in the `__init__.py` and thus the new sementic version as I have introduce breaking change. 

THe new function are all documented here: https://gee-tools.readthedocs.io/en/latest/

This first release includes the global refactoring of the `tools` package. but I didn't updated the `batch` module yet. This relative import cannot be resoved anymore as the file changed, let me try to find a quick fix.
